# START OF HYPRLAND CONFIG

monitor=,preferred,auto,1
$mod = SUPER
bind = $mod, RETURN, exec, kitty
bind = $mod, M, exit
exec-once = waybar
bind = $mod, r, exec, sh -c "pkill rofi || rofi -show drun"
# SWITCH WORKSPACES (SUPER + NUMBER)
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8

# MOVE WINDOW TO WORKSPACE ( SUPER + SHIFT  + NUMBER)
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8

exec-once = rot8
